# Generated by Django 4.1 on 2022-10-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminproducts',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='adminproducts',
            name='real_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
