# Generated by Django 4.1 on 2022-10-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0002_adminproducts_discount_adminproducts_real_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminproducts',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
