# Generated by Django 4.1 on 2022-10-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_commerce', '0003_alter_adminproducts_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminproducts',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
